---
title: Shannon and Clayton Wedding
timezone: Australia/Melbourne
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: shannonandclayton.wedding@gmail.com
description: |-
  Welcome to Shannon and Clayton's Wedding!

  This website has all the information for the wedding.
baseurl: 
url: http://shannonandclaytonwedding.com.au/
twitter_username: jekyllrb
github_username: Randy_Mustache
theme: minima
plugins:
- jekyll-feed
